### ISSUE TITLE
I can't understand how you manage nuget packages?

### ISSUE THREAD

**Issue by rpokrovskij** [MarinAtanasov/AppBrix.NetCore#1]
Hi, Marin.

I'm interesting to understand how you publish your nuget packages, especially `all` package.
Could you write several words?

It is not obvious, I can't find any script, but very interesting.

**Comment by MarinAtanasov** [comment]
Hi @rpokrovskij,

I am not entirely sure if this is what you mean, but these are the PowerShell scripts I used to package and publish the 0.12.0 version of the _Core_ Nuget packages.
```PowerShell
ForEach ($folder in (Get-ChildItem -Path Core -Directory)) { dotnet pack $folder.FullName -c Release }
ForEach ($folder in (Get-ChildItem -Path Core -Directory)) { nuget push "$($folder.FullName)\bin\Release\$($folder.Name).0.12.0.nupkg" }
```
I change _Core_ to _Modules_ and _Bundles_ to deploy the rest of the packages. And of course, I change the _0.12.0.nupkg_ version to whatever is the version currently being deployed.

You must set up Nuget CLI locally in order to use [nuget push](https://docs.microsoft.com/en-us/nuget/tools/cli-ref-push).

Please let me know if this helps clear things up or if you have any other questions.

**Comment by MarinAtanasov** [comment]
Hi @rpokrovskij. I have added a script for packaging and publishing all projects to nuget.org.
